aws_dbt_snowflake_project:
  outputs:
    dev:
      account: KUDPEZP-PJ13918
      database: AIRBNB
      password: DebojyotiMahto@2003
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: DEBU2003
      warehouse: COMPUTE_WH
  target: dev
